# Generated by Django 3.0 on 2019-12-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20191205_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='nombre',
        ),
    ]
