# Generated by Django 3.0 on 2019-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20191206_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raza',
            field=models.CharField(max_length=30),
        ),
    ]
