# Generated by Django 3.0 on 2019-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20191206_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
