# Generated by Django 3.0 on 2019-12-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20191206_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='encontrado',
            field=models.BooleanField(default=0),
        ),
    ]
