# Generated by Django 3.0 on 2019-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20191206_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
